    - name: Send information to ServiceNow
      shell: bash
      run: |
        ENDPOINT="https://krotondev.service-now.com/api/kra/release/create"
        LINK_EXTERNO="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        AUTH="YXBpLnVzZXI6MTpNd28tWzpxWHR7bC4/R311QyQ0MCxNam9XOTVqeHZebl0peDNsPw=="

        # Set default ORIGEM_RELEASE, INCIDENTE, SOLICITACAO_SERVICO, PROBLEMA, and DEMANDA values
        ORIGEM_RELEASE="Outros"
        INCIDENTE=""
        SOLICITACAO_SERVICO=""
        PROBLEMA=""
        DEMANDA=""
        OUTROS="Outros"

        # Check tags for incident, service request, problem or demand identifiers
        if [[ $TAGS == *"INC"* ]]; then
          INC_TAG=$(echo $TAGS | grep -o 'INC[0-9]*')
          ORIGEM_RELEASE="Incidente"
          INCIDENTE=$INC_TAG
          OUTROS=""
        elif [[ $TAGS == *"RITM"* ]]; then
          RITM_TAG=$(echo $TAGS | grep -o 'RITM[0-9]*')
          ORIGEM_RELEASE="Solicitação de Serviço"
          SOLICITACAO_SERVICO=$RITM_TAG
          OUTROS=""
        elif [[ $TAGS == *"PROB"* ]]; then
          PROB_TAG=$(echo $TAGS | grep -o 'PROB[0-9]*')
          ORIGEM_RELEASE="Problema"
          PROBLEMA=$PROB_TAG
          OUTROS=""
        elif [[ $TAGS == *"Demanda"* || $TAGS == *"demanda"* ]]; then
          DEMANDA_TAG=$(echo $TAGS | grep -o 'Demanda[0-9A-Za-z]*')
          ORIGEM_RELEASE="Demanda"
          DEMANDA=$DEMANDA_TAG
          OUTROS=""
        fi

        # Get the current time in São Paulo timezone
        SAO_PAULO_TIME=$(TZ="America/Sao_Paulo" date +"%Y-%m-%dT%H:%M:%S")

        PAYLOAD=$(cat <<EOF
        {
          "origemCriacao": "GitHub",
          "abertoPor": "${{ github.actor }}",
          "aprovadoPor": [$APROVADORES_EMAIL],
          "trem": "${{ inputs.TREM }}",
          "grupo": "${{ inputs.GRUPO }}",
          "classificacao": "Manutenção Corretiva",
          "itemConfiguracao": "$SERVICO",
          "bu": "Cogna",
          "origemRelease": "$ORIGEM_RELEASE",
          "incidente": "$INCIDENTE",
          "solicitacaoServico": "$SOLICITACAO_SERVICO",
          "problema": "$PROBLEMA",
          "demanda": "$DEMANDA",
          "outros": "$OUTROS",
          "titulo": "Build ${{ github.run_id }}",
          "descricao": "Descrição detalhada do build ${{ github.run_id }}",
          "inicioReal": "$SAO_PAULO_TIME",
          "terminoReal": "$SAO_PAULO_TIME",
          "fechamento": "Encerrada com sucesso",
          "linkExterno": "$LINK_EXTERNO"
        }
        EOF
        )

        echo "Payload to be sent:"
        echo "$PAYLOAD"

        curl -X POST "$ENDPOINT" \
             -H "Authorization: Basic $AUTH" \
             -H "Content-Type: application/json" \
             -d "$PAYLOAD"
